routes/web.php
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'M Qadafi',
            'stuff' => 'Scanner',
            'qty' => '1',
            'status' => '<span class="badge badge-pill badge-primary">DIPINJAM</span>',
            'borrow_at' => '23 September 2001',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Daftar Permintaan Peminjaman
Route::post('apiborreq', function () {
    $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
    $act .= '<i class="fa fa-ellipsis-h"></i>';
    $act .= '</a>';
    $act .= '<div class="dropdown-menu" style="width:50px;">';
    $act .= '<a class="dropdown-item" href="javascript:void(0)">Terima</a>';
    $act .= '<a class="dropdown-item" href="javascript:void(0)">Tolak</a>';
    $act .= '</div>';
    $data = array(
        array(
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'Slim My Man',
            'stuff' => 'Acer ROG XXX',
            'qty' => '1',
            'status' => '<span class="badge badge-pill badge-info">PENDING</span>',
            'borrow_at' => '23 September 2001',
            'action' => $act
        ),
        array(
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'M Qadafi',
            'stuff' => 'Scanner',
            'qty' => '1',
            'status' => '<span class="badge badge-pill badge-info">PENDING</span>',
            'borrow_at' => '23 September 2001',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Daftar Peminjaman (Peminjam)
Route::post('apipeminjam', function () {
    $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
    $act .= '<i class="fa fa-ellipsis-h"></i>';
    $act .= '</a>';
    $act .= '<div class="dropdown-menu" style="width:50px;">';
    $act .= '<a class="dropdown-item" href="'.route('peminjam.borrow.detail', 45).'">Detail</a>';
    $act .= '</div>';
    $data = array(
        array(
            'id' => '51242',
            'qty' => 3,
            'borrow_at' => '20/02/2019',
            'status' => '<span class="badge badge-pill badge-default">PENDING</span>',
            'action' => $act
        ),
        array(
            'id' => '51244',
            'qty' => 3,
            'borrow_at' => '25/02/2019',
            'status' => '<span class="badge badge-pill badge-default">PENDING</span>',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Auth Section
Route::prefix('auth')->name('auth.')->group(function () {
    Route::get('login', function () {
        return view('auth/login');
    })->name('login')->middleware('guest');
    
    Route::get('register', function () {
        return view('auth/register');
    })->name('register')->middleware('guest');
});

// Modal API
// Route::prefix('modal')->middleware('auth')->name('modal.')->group(function () {
Route::prefix('modal')->name('modal.')->group(function () {
    Route::post('user', function () {
        return view('user/modal/_detail');
    })->name('user');

    Route::post('invent', function () {
        return view('inventory/modal/_invent');
    })->name('invent');

    Route::post('borrow', function () {
        return view('borrow/modal/_borrow');
    })->name('borrow');
});

// Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');

    Route::get('profile', function () {
        return view('profile');
    })->name('profile');

    Route::prefix('inventaris')->name('invent.')->group(function () {
        Route::get('inventarisir', function () {
            return view('inventory/index');
        })->name('index');

        Route::get('ruangan', function () {
            return view('inventory/room');
        })->name('room');

        Route::get('tipe', function () {
            return view('inventory/type');
        })->name('type');

        Route::get('tambah-barang', function () {
            return view('inventory/create__invent');
        })->name('create_invent');

        Route::get('edit-barang/{slug}', function () {
            return view('inventory/create__invent');
        })->name('edit_invent');

        Route::get('tambah-ruangan', function () {
            return view('inventory/create__room');
        })->name('create_room');

        Route::get('edit-ruangan/{id}', function () {
            return view('inventory/create__room');
        })->name('edit_room');

        Route::get('tambah-tipe', function () {
            return view('inventory/create__type');
        })->name('create_type');

        Route::get('edit-tipe/{id}', function () {
            return view('inventory/create__type');
        })->name('edit_type');

        Route::get('label/{code}', function ($code) {
            $barcode = new BarcodeGenerator();
            $barcode->setText($code);
            $barcode->setType(BarcodeGenerator::Code128);
            $barcode->setScale(2);
            $barcode->setThickness(25);
            $barcode->setFontSize(10);
            $code = $barcode->generate();

            return view('inventory/label', compact('code'));
        })->name('label');

        Route::get('report', function () {
            return view('admin/report');
        })->name('report');
    });

    Route::prefix('peminjaman')->name('borrow.')->group(function () {
        Route::get('/daftar', function () {
            return view('borrow/index');
        })->name('index');

        Route::get('/permintaan', function () {
            return view('borrow/request');
        })->name('request');

        Route::get('/tambah', function () {
            return view('borrow/create');
        })->name('create');

        Route::get('/edit/{id}', function () {
            return view('borrow/create');
        })->name('edit');
    });

    Route::prefix('pengguna')->name('user.')->group(function () {
        Route::get('/daftar', function () {
            return view('user/index');
        })->name('index');

        Route::get('/permintaan', function () {
            return view('user/request');
        })->name('request');

        Route::get('/tambah', function () {
            return view('user/create');
        })->name('create');

        Route::get('/edit/{id}', function () {
            return view('user/create');
        })->name('edit');
    });

    Route::get('/log', function () {
        // activity()
        // ->withProperties([
        //     'object' => 'Acer ROG XXX', 
        //     'by' => '<b>Slim My Man</b>'
        // ])
        // ->log('ingin melakukan peminjaman');
        $act = Activity::all();

        return view('admin/activity', compact('act'));
    })->name('log');
});

// Route::prefix('operator')->name('operator.')->middleware('operator')->group(function () {
Route::prefix('operator')->name('operator.')->group(function () {
    Route::get('/', function () {
        return view('operator/index');
    })->name('index');
    
    Route::get('profile', function () {
        return view('profile');
    })->name('profile');

    Route::get('/peminjaman/daftar', function () {
        return view('operator/index');
    });

    Route::prefix('inventaris')->name('invent.')->group(function () {
        Route::get('inventarisir', function () {
            return view('inventory/index');
        })->name('index');

        Route::get('ruangan', function () {
            return view('inventory/room');
        })->name('room');

        Route::get('tipe', function () {
            return view('inventory/type');
        })->name('type');

        Route::get('tambah-barang', function () {
            return view('inventory/create__invent');
        })->name('create_invent');

        Route::get('edit-barang/{slug}', function () {
            return view('inventory/create__invent');
        })->name('edit_invent');

        Route::get('label', function () {
            $barcode = new BarcodeGenerator();
            $barcode->setText("0123456789");
            $barcode->setType(BarcodeGenerator::Code128);
            $barcode->setScale(2);
            $barcode->setThickness(25);
            $barcode->setFontSize(10);
            $code = $barcode->generate();

            return view('inventory/label', compact('code'));
        })->name('label');
    });

    Route::prefix('peminjaman')->name('borrow.')->group(function () {
        Route::get('/daftar', function () {
            return view('borrow/index');
        })->name('index');

        Route::get('/permintaan', function () {
            return view('borrow/request');
        })->name('request');

        Route::get('/tambah', function () {
            return view('borrow/create');
        })->name('create');
    });
});

// Route::prefix('peminjam')->name('peminjam.')->middleware('borrower')->group(function() {
Route::prefix('peminjam')->name('peminjam.')->group(function() {
    Route::get('/', function() {
        return view('peminjam/index');
    })->name('index');

    Route::get('/profile', function() {
        return view('profile');
    })->name('profile');

    Route::get('/keranjang', function() {
        return view('peminjam/keranjang');
    })->name('keranjang');

    Route::prefix('peminjaman')->name('borrow.')->group(function () {
        Route::get('daftar', function () {
            return view('peminjam/list-peminjaman');
        })->name('list');

        Route::get('detail/{id}', function () {
            return view('peminjam/detail-peminjaman');
        })->name('detail');
    });

    Route::prefix('inventaris')->name('invent.')->group(function () {

app/Inventory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Type;
use App\Room;
use App\Borrow;
use App\BorrowDetail;
use App\User;

class Inventory extends Model
{
    protected $fillable = ['user_id', 'type_id', 'room_id', 'code', 'name', 'condition', 'desc', 'qty', 'picture'];

    public function type () 
    {
        return $this->belongsTo(Type::class);
    }

    public function room ()
    {
        return $this->belongsTo(Room::class);
    }

    public function user ()
    {
        return $this->belongsTo(User::class);
    }

    public function borrow ()
    {
        return $this->belongsToMany(Borrow::class);
    }

    public function borrowDetail () 
    {
        return $this->hasMany(BorrowDetail::class);
    }

    public function setNameAttribute ($name)
    {
        $this->attributes['name'] = $name;
        $this->attributes['slug'] = str_slug($name);
    }

    public function getUrlAttribute ()
    {
        if(Auth::user()->level_id === 3) {
            return route('admin.invent.edit_invent', $this->slug);
        } else {
            return route('operator.invent.edit_invent', $this->slug);
        }
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class InventoryController extends Controller
{
    //
}

resources/views/inventory/create__invent.blade.php
@extends('template')

@section('content')
    
    <div class="row mt-3">
        <div class="col-lg-12">

            <div class="card card-base">
                <h6 class="card-header">Form Tambah Barang</h6>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-12">
                            <form action="" method="post">
                                <div class="row">

                                    <div class="col-md-3">
                                        <div class="choose-photo bg-light">
                                            <img src="" class="img-fluid" id="img-file">
                                        </div>
                                    </div>

                                    <div class="col-md-9">
                                        <input type="file" name="picture" class="img-preview d-none">
                                        <div class="row">
                                            <div class="col-md-7">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Nama barang</label>
                                                    <input type="text" class="form-control">
                                                </div>
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Tipe barang</label>
                                                    <select name="" id="" class="form-control">
                                                        <option value="">A</option>
                                                        <option value="">B</option>
                                                        <option value="">C</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Kode barang</label>
                                                    <div class="input-group input-group-alternative mb-4">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text">A1</i></span>
                                                        </div>
                                                        <input class="form-control form-control-alternative" type="text">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Ruangan</label>
                                                    <select name="" id="" class="form-control">
                                                        <option value="">A</option>
                                                        <option value="">B</option>
                                                        <option value="">C</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Kondisi barang</label>
                                                    <select name="" id="" class="form-control">
                                                        <option value="">A</option>
                                                        <option value="">B</option>
                                                        <option value="">C</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-2">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Stok</label>
                                                    <input type="text" class="form-control">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="row mt-3">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('admin.invent.index') }}" class="btn btn-secondary btn-rounded">Cancel</a>
                                        &nbsp;
                                        <input type="submit" class="btn btn-base btn-rounded">
                                    </div>
                                </div>                
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/inventory/create__room.blade.php
@extends('template')

@section('content')
    
    <div class="row mt-3">
        <div class="col-lg-12">

            <div class="card card-base">
                <h6 class="card-header">Form Tambah Ruangan</h6>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-12">
                            <form action="" method="post">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Kode</label>
                                            <input type="text" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-7">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Nama</label>
                                            <input type="text" class="form-control">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Deskripsi</label>
                                            <textarea name="" rows="4" class="form-control"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('admin.invent.room') }}" class="btn btn-secondary btn-rounded">Cancel</a>
                                        &nbsp;
                                        <input type="submit" class="btn btn-base btn-rounded">
                                    </div>
                                </div>                
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/inventory/create__type.blade.php
@extends('template')

@section('content')
    
    <div class="row mt-3">
        <div class="col-lg-12">

            <div class="card card-base">
                <h6 class="card-header">Form Tambah Tipe Barang</h6>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-12">
                            <form action="" method="post">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Kode</label>
                                            <input type="text" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-7">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Nama</label>
                                            <input type="text" class="form-control">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Deskripsi</label>
                                            <textarea name="" rows="4" class="form-control"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('admin.invent.type') }}" class="btn btn-secondary btn-rounded">Cancel</a>
                                        &nbsp;
                                        <input type="submit" class="btn btn-base btn-rounded">
                                    </div>
                                </div>                
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/inventory/index.blade.php
@extends('template')

@section('content')

    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-9">
                            <form class="form-inline">
                                <div class="form-group">
                                    <div class="input-group input-group-merge">
                                        <input class="form-control" placeholder="Search" type="text" id="search">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-search"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group ml-3">
                                    <select id="sortBy" class="form-control">
                                        <option>Sort By</option>
                                        <option value="asc">Name (A-Z)</option>
                                        <option value="desc">Name (Z-A)</option>
                                    </select>
                                </div>
                            </form>	
                        </div>
                        <div class="col-sm-3 text-right">
                            <a href="{{ route('admin.invent.create_invent') }}" class="btn btn-base btn-rounded">
                                <i class="fa fa-plus"></i> Tambah Barang
                            </a>
                        </div>
                    </div>
                            
                    <div class="row mt-2">
                        <table id="myTable" class="table mt-3">
                            <thead class="thead-base">
                                <tr>
                                    <th width="10"></th>
                                    <th>Nama</th>
                                    <th width="100">Ruangan</th>
                                    <th width="100">Kode Barang</th>
                                    <th width="80" class="text-center">Kondisi</th>
                                    <th width="80" class="text-center">Stok</th>
                                    <th width="50">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>    
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>
        var table;
        $(function () {
            table = $('#myTable').dataTable({
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "bSort": true,
                "bFilter": true,
                "sDom": 'ltipr',
                "processing": true,
                "serverside": true,
                "ajax": {
                    url: '{{ url("/apiinvent") }}',
                    type: "POST"
                },
                "columns": [
                    {"data": "picture", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "name", "sClass": "hide-sort align-middle", "bSortable": true},
                    {"data": "room_id", "sClass": "align-middle", "bSortable": false},
                    {"data": "code", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "condition", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "qty", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "action", "sClass": "text-center align-middle", "bSortable": false}
                ],
                "aaSorting": [[1, "asc"]],
                "drawCallback": function (settings) {
                    $('.tip-right').tooltip({
                        container: 'body',
                        placement: 'right'
                    });
                }
            });

            $(".dataTables_length").remove();
            $(".mytable_filter").remove();

            $("#search").keyup(function(){
                table.fnFilter($(this).val());
            });

            $("#sortBy").change(function(){
                var val = $(this).val();
                table.fnSort([1, val]);
            });
        });

        function printLabel(id) {
            swal({
                title: "Apakah Anda ingin print labelnya ?",
                text: "Klik tombol \'ok\' untuk lanjut !",
                icon: "info",
                buttons: true,
                dangerMode: false,
            })
            .then((willPrint) => {
                if (willPrint) {
                    window.open("{{ url('admin/inventaris/label/') }}/" + id, '_blank');
                    window.focus();
                } else {
                    swal("Anda batal print label!");
                }
            });
        }

        function deleteData(id) {
            swal({
                title: "Data ini akan dihapus secara permanen!",
                text: "Apakah Anda yakin?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    swal("Selamat! Data Anda berhasil dihapus!", {
                    icon: "success",
                    });
                } else {
                    swal("Anda batal menghapus!");
                }
            });
        }

        function showData(id) {
            var formData = new FormData();
            formData.append('id', id);
            axios.post("{{ route('modal.invent') }}", formData)
            .then(function(html){
                $('#loadContent').html(html.data);
                $('#myModal').modal('show');
            }).catch(function(err) {
                console.log(err);
            })
        }
    </script>
@endsection

resources/views/inventory/label.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>INSCHOOL — {{ ucfirst(Request::segment(2) ?? "beranda") }}</title>

    {{-- Favicon --}}
    <link rel="shortcut icon" href="{{ asset('img/logo/inschool.png') }}" type="image/x-icon">
</head>
<style>
    body {
        border: 1px solid black;
        width: 29mm;
        height: 89.8mm;
    }

    .img-smk {
        transform: rotate(90deg) translate(5%, -55%);
    }

    .img-label {
        margin-right: 5px;
        margin-left: 5px;
        transform: rotate(90deg) translate(36%, 105%);
    }

    .img-logo {
        transform: rotate(90deg) translate(285%, -55%);
    }
</style>
<body>
    <div style="margin: auto;">
        <img src="{{ asset('img/logo/smkn1.jpg') }}" style="width:55px;height:55px;" class="img-smk">
        <img src="data:image/png;base64,{{ $code }}" class="img-label" />
        <img src="{{ asset('img/logo/inschool.png') }}" style="width:55px;height:55px;" class="img-logo">
    </div style="margin: auto;">
    <div style="position: relative; top: 160px;">
        <small>
            <strong>Ruangan</strong>
            <br>
            Ruang D8
            <br>
            <strong>Nama Barang</strong>
            <br>
            ACER ROG XXX XXX
        </small>
    </div>
</body>
<script>
    // window.print()
</script>
</html>