routes/web.php
    $act .= '<div class="dropdown-menu" style="width:50px;">';
    $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="showData(1)">Detail</a>';
    $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="printLabel(\'A1-0001\')">Print Label</a>';
    $act .= '<a class="dropdown-item" href="'.route("admin.invent.edit_invent", 1).'">Edit</a>';
    $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="deleteData(1)">Delete</a>';
    $act .= '</div>';
    $data = array(
        array(
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'Acer ROG XXX',
            'room_id' => 'Ruangan D8',
            'code' => 'A1-0001',
            'condition' => '<span class="badge badge-pill badge-primary">Baik</span>',
            'qty' => '10',
            'action' => $act
        ),
        array(
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'Barcode Scanner',
            'room_id' => 'Ruangan D8',
            'code' => 'B1-0001',
            'condition' => '<span class="badge badge-pill badge-primary">Baik</span>',
            'qty' => '1',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Daftar Ruangan
Route::post('apiroom', function () {
    $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
    $act .= '<i class="fa fa-ellipsis-h"></i>';
    $act .= '</a>';
    $act .= '<div class="dropdown-menu" style="width:50px;">';
    // if(Auth::user()->level_id === 3) {
        $act .= '<a class="dropdown-item" href="'.route("admin.invent.edit_room", 1).'">Edit</a>';
        $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="deleteData(1)">Delete</a>';
    // }
    $act .= '</div>';
    $data = array(
        array(
            'code' => 'D9',
            'name' => 'Ruang 28',
            'desc' => 'Ruang penyimpanan jodoh',
            'action' => $act
        ),
        array(
            'code' => 'D10',
            'name' => 'Ruang 29',
            'desc' => 'Ruang penyimpanan hati',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Daftar Tipe Barang
Route::post('apitype', function () {
    $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
    $act .= '<i class="fa fa-ellipsis-h"></i>';
    $act .= '</a>';
    $act .= '<div class="dropdown-menu" style="width:50px;">';
    // if(Auth::user()->level_id === 3) {
        $act .= '<a class="dropdown-item" href="'.route("admin.invent.edit_type", 1).'">Edit</a>';
        $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="deleteData(1)">Delete</a>';
    // }
    $act .= '</div>';
    $data = array(
        array(
            'code' => 'A1',
            'name' => 'Teknologi',
            'desc' => 'Contoh: Komputer, Monitor, Mouse, Keyboard, dst.',
            'action' => $act
        ),
        array(
            'code' => 'A2',
            'name' => 'Elektronik',
            'desc' => 'Contoh: Setrika, Kabel Roll, dst.',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Daftar Peminjaman
Route::post('apiborrow', function () {
    $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
    $act .= '<i class="fa fa-ellipsis-h"></i>';
    $act .= '</a>';
    $act .= '<div class="dropdown-menu" style="width:50px;">';
    $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="showData(1)">Detail</a>';
    $act .= '<a class="dropdown-item" href="'.route("admin.borrow.edit", 1).'">Edit</a>';
    $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="deleteData(1)">Delete</a>';
    $act .= '</div>';
    $data = array(
        array(
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'Slim My Man',
            'stuff' => 'Acer ROG XXX',
            'qty' => '1',
            'status' => '<span class="badge badge-pill badge-primary">DIPINJAM</span>',
            'borrow_at' => '23 September 2001',
            'action' => $act
        ),
        array(
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'M Qadafi',
            'stuff' => 'Scanner',
            'qty' => '1',
            'status' => '<span class="badge badge-pill badge-primary">DIPINJAM</span>',
            'borrow_at' => '23 September 2001',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Daftar Permintaan Peminjaman
Route::post('apiborreq', function () {
    $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
    $act .= '<i class="fa fa-ellipsis-h"></i>';
    $act .= '</a>';
    $act .= '<div class="dropdown-menu" style="width:50px;">';
    $act .= '<a class="dropdown-item" href="javascript:void(0)">Terima</a>';
    $act .= '<a class="dropdown-item" href="javascript:void(0)">Tolak</a>';
    $act .= '</div>';
    $data = array(
        array(
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'Slim My Man',
            'stuff' => 'Acer ROG XXX',
            'qty' => '1',
            'status' => '<span class="badge badge-pill badge-info">PENDING</span>',
            'borrow_at' => '23 September 2001',
            'action' => $act
        ),
        array(
            'picture' => '<img src="'.asset('img/no-photo.png').'" class="img-round img-thumb">',
            'name' => 'M Qadafi',
            'stuff' => 'Scanner',
            'qty' => '1',
            'status' => '<span class="badge badge-pill badge-info">PENDING</span>',
            'borrow_at' => '23 September 2001',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Daftar Peminjaman (Peminjam)
Route::post('apipeminjam', function () {
    $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
    $act .= '<i class="fa fa-ellipsis-h"></i>';
    $act .= '</a>';
    $act .= '<div class="dropdown-menu" style="width:50px;">';
    $act .= '<a class="dropdown-item" href="'.route('peminjam.borrow.detail', 45).'">Detail</a>';
    $act .= '</div>';
    $data = array(
        array(
            'id' => '51242',
            'qty' => 3,
            'borrow_at' => '20/02/2019',
            'status' => '<span class="badge badge-pill badge-default">PENDING</span>',
            'action' => $act
        ),
        array(
            'id' => '51244',
            'qty' => 3,
            'borrow_at' => '25/02/2019',
            'status' => '<span class="badge badge-pill badge-default">PENDING</span>',
            'action' => $act
        )
    );

    echo json_encode(array("sEcho" => 1, "aaData" => $data));
});

// Auth Section
Route::prefix('auth')->name('auth.')->group(function () {
    Route::get('login', function () {
        return view('auth/login');
    })->name('login')->middleware('guest');
    
    Route::get('register', function () {
        return view('auth/register');
    })->name('register')->middleware('guest');
});

// Modal API
// Route::prefix('modal')->middleware('auth')->name('modal.')->group(function () {
Route::prefix('modal')->name('modal.')->group(function () {
    Route::post('user', function () {
        return view('user/modal/_detail');
    })->name('user');

    Route::post('invent', function () {
        return view('inventory/modal/_invent');
    })->name('invent');

    Route::post('borrow', function () {
        return view('borrow/modal/_borrow');
    })->name('borrow');
});

// Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');

    Route::get('profile', function () {
        return view('profile');
    })->name('profile');

    Route::prefix('inventaris')->name('invent.')->group(function () {
        Route::get('inventarisir', function () {
            return view('inventory/index');
        })->name('index');

        Route::get('ruangan', function () {
            return view('inventory/room');
        })->name('room');

        Route::get('tipe', function () {
            return view('inventory/type');
        })->name('type');

        Route::get('tambah-barang', function () {
            return view('inventory/create__invent');
        })->name('create_invent');

        Route::get('edit-barang/{slug}', function () {
            return view('inventory/create__invent');
        })->name('edit_invent');

        Route::get('tambah-ruangan', function () {
            return view('inventory/create__room');
        })->name('create_room');

        Route::get('edit-ruangan/{id}', function () {
            return view('inventory/create__room');
        })->name('edit_room');

        Route::get('tambah-tipe', function () {
            return view('inventory/create__type');
        })->name('create_type');

        Route::get('edit-tipe/{id}', function () {
            return view('inventory/create__type');
        })->name('edit_type');

        Route::get('label/{code}', function ($code) {
            $barcode = new BarcodeGenerator();
            $barcode->setText($code);
            $barcode->setType(BarcodeGenerator::Code128);
            $barcode->setScale(2);
            $barcode->setThickness(25);
            $barcode->setFontSize(10);
            $code = $barcode->generate();

            return view('inventory/label', compact('code'));
        })->name('label');

        Route::get('report', function () {
            return view('admin/report');
        })->name('report');
    });

app/Borrow.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Borrower;
use App\Inventory;
use App\BorrowDetail;

class Borrow extends Model
{
    protected $fillable = ['borrower_id', 'borrow_at', 'return_at'];

    public function borrower ()
    {
        return $this->belongsTo(Borrower::class);
    }

    public function inventory ()
    {
        return $this->belongToMany(Inventory::class);
    }

    public function borrowDetail () 
    {
        return $this->hasMany(BorrowDetail::class);
    }
}

resources/views/borrow/create.blade.php
@extends('template')

@section('content')
    
    <div class="row mt-3">
        <div class="col-lg-12">

            <div class="card card-base">
                <h6 class="card-header">Form Tambah Peminjaman</h6>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-12">
                            <form action="" method="post">
                                <div class="row">

                                    <div class="col-md-3">
                                        <div class="choose-photo bg-light">
                                            <img src="" class="img-fluid">
                                        </div>
                                    </div>

                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Kode barang</label>
                                                    <input type="text" class="form-control" autofocus>
                                                </div>
                                            </div>

                                            <div class="col-md-7">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Nama barang</label>
                                                    <input type="text" class="form-control">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-2">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Tipe barang</label>
                                                    <select name="" id="" class="form-control">
                                                        <option value="">A</option>
                                                        <option value="">B</option>
                                                        <option value="">C</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Ruangan</label>
                                                    <select name="" id="" class="form-control">
                                                        <option value="">A</option>
                                                        <option value="">B</option>
                                                        <option value="">C</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Kondisi barang</label>
                                                    <select name="" id="" class="form-control">
                                                        <option value="">A</option>
                                                        <option value="">B</option>
                                                        <option value="">C</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-2">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Jumlah</label>
                                                    <input type="text" class="form-control">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Tanggal Pinjam</label>
                                                    <div class="input-group input-group-alternative">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text"><i class="ni ni-calendar-grid-58"></i></span>
                                                        </div>
                                                        <input class="form-control datepicker" placeholder="Select date" type="text" value="{{ date('m/d/Y') }}">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Tanggal Kembali</label>
                                                    <div class="input-group input-group-alternative">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text"><i class="ni ni-calendar-grid-58"></i></span>
                                                        </div>
                                                        <input class="form-control datepicker" placeholder="Select date" type="text" value="">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Status</label>
                                                    <select name="" class="form-control">
                                                        <option value="">Pending</option>
                                                        <option value="">Dipinjam</option>
                                                        <option value="">Ditolak</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="row mt-3">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('admin.borrow.index') }}" class="btn btn-secondary btn-rounded">Cancel</a>
                                        &nbsp;
                                        <input type="submit" class="btn btn-base btn-rounded">
                                    </div>
                                </div>                
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/borrow/index.blade.php
@extends('template')

@section('content')

    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-9">
                            <form class="form-inline">
                                <div class="form-group">
                                    <div class="input-group input-group-merge">
                                        <input class="form-control" placeholder="Search" type="text" id="search">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-search"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group ml-3">
                                    <select id="sortBy" class="form-control">
                                        <option>Sort By</option>
                                        <option value="asc">Name (A-Z)</option>
                                        <option value="desc">Name (Z-A)</option>
                                    </select>
                                </div>
                            </form>	
                        </div>
                        <div class="col-sm-3 text-right">
                            <a href="{{ route('admin.borrow.create') }}" class="btn btn-base btn-rounded">
                                <i class="fa fa-plus"></i> Tambah Peminjaman
                            </a>
                        </div>
                    </div>
                            
                    <div class="row mt-2">
                        <table id="myTable" class="table mt-3">
                            <thead class="thead-base">
                                <tr>
                                    <th width="5"></th>
                                    <th width="230">Nama Peminjam</th>
                                    <th width="180">Barang</th>
                                    <th width="80" class="text-center">Jumlah</th>
                                    <th width="80" class="text-center">Status</th>
                                    <th width="150"class="text-center">Waktu Peminjaman</th>
                                    <th width="50" class="text-center">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>    
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>
        var table;
        $(function () {
            table = $('#myTable').dataTable({
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "bSort": true,
                "bFilter": true,
                "sDom": 'ltipr',
                "processing": true,
                "serverside": true,
                "ajax": {
                    url: '{{ url("/apiborrow") }}',
                    type: "POST"
                },
                "columns": [
                    {"data": "picture", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "name", "sClass": "hide-sort align-middle", "bSortable": true},
                    {"data": "stuff", "sClass": "align-middle", "bSortable": false},
                    {"data": "qty", "sClass": "text-center text-bold align-middle", "bSortable": false},
                    {"data": "status", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "borrow_at", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "action", "sClass": "text-center align-middle", "bSortable": false}
                ],
                "aaSorting": [[1, "asc"]],
                "drawCallback": function (settings) {
                    $('.tip-right').tooltip({
                        container: 'body',
                        placement: 'right'
                    });
                }
            });

            $(".dataTables_length").remove();
            $(".mytable_filter").remove();

            $("#search").keyup(function(){
                table.fnFilter($(this).val());
            });

            $("#sortBy").change(function(){
                var val = $(this).val();
                table.fnSort([1, val]);
            });
        });

        function deleteData(id) {
            swal({
                title: "Data ini akan dihapus secara permanen!",
                text: "Apakah Anda yakin?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    swal("Selamat! Data Anda berhasil dihapus!", {
                    icon: "success",
                    });
                } else {
                    swal("Anda batal menghapus!");
                }
            });
        }

        function showData(id) {
            var formData = new FormData();
            formData.append('id', id);
            axios.post("{{ route('modal.borrow') }}", formData)
            .then(function(html){
                $('#loadContent').html(html.data);
                $('#myModal').modal('show');
            }).catch(function(err) {
                console.log(err);
            })
        }
    </script>
@endsection

resources/views/borrow/request.blade.php
@extends('template')

@section('content')

    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-9">
                            <form class="form-inline">
                                <div class="form-group">
                                    <div class="input-group input-group-merge">
                                        <input class="form-control" placeholder="Search" type="text" id="search">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-search"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group ml-3">
                                    <select id="sortBy" class="form-control">
                                        <option>Sort By</option>
                                        <option value="asc">Name (A-Z)</option>
                                        <option value="desc">Name (Z-A)</option>
                                    </select>
                                </div>
                            </form>	
                        </div>
                    </div>
                            
                    <div class="row mt-2">
                        <table id="myTable" class="table mt-3">
                            <thead class="thead-base">
                                <tr>
                                    <th width="5"></th>
                                    <th width="230">Nama Peminjam</th>
                                    <th width="180">Barang</th>
                                    <th width="80" class="text-center">Jumlah</th>
                                    <th width="80" class="text-center">Status</th>
                                    <th width="150"class="text-center">Waktu Peminjaman</th>
                                    <th width="50" class="text-center">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>    
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>
        var table;
        $(function () {
            table = $('#myTable').dataTable({
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "bSort": true,
                "bFilter": true,
                "sDom": 'ltipr',
                "processing": true,
                "serverside": true,
                "ajax": {
                    url: '{{ url("/apiborreq") }}',
                    type: "POST"
                },
                "columns": [
                    {"data": "picture", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "name", "sClass": "hide-sort align-middle", "bSortable": true},
                    {"data": "stuff", "sClass": "align-middle", "bSortable": false},
                    {"data": "qty", "sClass": "text-center text-bold align-middle", "bSortable": false},
                    {"data": "status", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "borrow_at", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "action", "sClass": "text-center align-middle", "bSortable": false}
                ],
                "aaSorting": [[1, "asc"]],
                "drawCallback": function (settings) {
                    $('.tip-right').tooltip({
                        container: 'body',
                        placement: 'right'
                    });
                }
            });

            $(".dataTables_length").remove();
            $(".mytable_filter").remove();

            $("#search").keyup(function(){
                table.fnFilter($(this).val());
            });

            $("#sortBy").change(function(){
                var val = $(this).val();
                table.fnSort([1, val]);
            });
        });
    </script>
@endsection